name: Build and Publish images

on:
  push:

jobs:
  build-and-push-docker-image:
    name: Build Docker images and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Declare variables
        id: vars
        run: echo "::set-output name=version::$(echo ${GITHUB_SHA} | cut -c1-8)"
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Account service - build and push
        uses: docker/build-push-action@v2
        with:
          context: ./ml4fakenews-accounts
          push: true
          tags: randomstudent/ml4fakenews-accounts:${{ steps.vars.outputs.version }}

      # - name: Email service - build and push
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./ml4fakenews-email-service
      #     push: true
      #     tags: docker.io/randomstudent/ml4fakenews-email-service:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
