name: Test

on:
  workflow_dispatch:
  push:


jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Test Account microservice
        run: mvn -f ./ml4fakenews-accounts/pom.xml -B clean verify
      - name: Test Email microservice
        run: mvn -f ./ml4fakenews-email-service/pom.xml -B clean verify
      - name: Test Subscriptions microservice
        run: mvn -f ./ml4fakenews-subscriptions/pom.xml -B clean verify
